version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: dt_rag_postgres
    environment:
      POSTGRES_DB: dt_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: dt_rag_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
