# Prometheus 설정
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Dynamic Taxonomy RAG API 메트릭
  - job_name: 'dt-rag-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # PostgreSQL 메트릭 (postgres_exporter 사용 시)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    # 현재는 비활성화 (postgres_exporter 별도 설정 필요)
    
  # Redis 메트릭 (redis_exporter 사용 시)  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    # 현재는 비활성화 (redis_exporter 별도 설정 필요)