name: PR Validate (Build/Test/Lint/DB + Auto Report)
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app_test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect docs-only changes
        run: |
          git diff --name-only origin/${{ github.base_ref }}...HEAD | \
          grep -vE '^(docs/|README.md|.*\.md)$' >/dev/null \
          && echo "SKIP=0" >> $GITHUB_ENV || echo "SKIP=1" >> $GITHUB_ENV

      # ---------- Python (있을 때만) ----------
      - name: Set up Python
        if: hashFiles('requirements.txt') != '' && env.SKIP == '0'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        if: hashFiles('requirements.txt') != '' && env.SKIP == '0'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install Python deps
        if: hashFiles('requirements.txt') != '' && env.SKIP == '0'
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff alembic

      - name: DB migrate dry-run (Alembic)
        if: hashFiles('alembic.ini') != '' && env.SKIP == '0'
        run: |
          alembic upgrade head
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Alembic rollback smoke test
        if: hashFiles('alembic.ini') != '' && env.SKIP == '0'
        run: |
          echo "Testing rollback safety..."
          alembic upgrade head
          alembic downgrade -1
          alembic upgrade head
          echo "Rollback smoke test completed successfully"
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      - name: Lint (ruff → annotations)
        if: hashFiles('requirements.txt') != '' && env.SKIP == '0'
        run: |
          ruff check . --output-format=github
        continue-on-error: true

      - name: Test (pytest → JUnit)
        id: pytest
        if: hashFiles('requirements.txt') != '' && env.SKIP == '0'
        run: |
          mkdir -p reports
          set +e
          pytest -q --disable-warnings --maxfail=0 --junitxml=reports/pytest.xml
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          exit 0
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}

      # ---------- Node/JS (있을 때만) ----------
      - name: Set up Node
        if: hashFiles('package.json') != '' && env.SKIP == '0'
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache npm
        if: hashFiles('package.json') != '' && env.SKIP == '0'
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

      - name: Install Node deps
        if: hashFiles('package.json') != '' && env.SKIP == '0'
        run: npm ci

      - name: Lint (eslint → annotations)
        if: hashFiles('package.json') != '' && env.SKIP == '0'
        run: |
          npx eslint . -f stylish || true

      - name: Contract Lint (OpenAPI optional)
        if: hashFiles('openapi.yaml', 'openapi.yml', 'openapi.json') != '' && env.SKIP == '0'
        run: |
          FILE=$(ls openapi.yaml openapi.yml openapi.json 2>/dev/null | head -n1)
          npx -y @redocly/cli@latest lint "$FILE" || npx -y @stoplight/spectral-cli@latest lint "$FILE"

      - name: Test (npm test)
        id: npmtest
        if: hashFiles('package.json') != '' && env.SKIP == '0'
        run: |
          mkdir -p reports
          set +e
          npm test --silent 2>&1 | tee reports/npm-test.log
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          exit 0

      # ---------- 아티팩트/요약/라벨/코멘트 ----------
      - name: Upload reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Prepare failure summary
        if: always()
        run: |
          echo "## 🔍 Failure Summary" > failure_summary.md
          echo "" >> failure_summary.md
          if [ -f reports/pytest.xml ]; then
            echo "### Python Test Failures (Top 10)" >> failure_summary.md
            echo '```' >> failure_summary.md
            grep -E "(FAILED|ERROR)" reports/pytest.xml | head -10 >> failure_summary.md || true
            echo '```' >> failure_summary.md
            echo "" >> failure_summary.md
          fi
          if [ -f reports/npm-test.log ]; then
            echo "### Node.js Test Failures (Top 10)" >> failure_summary.md
            echo '```' >> failure_summary.md
            head -20 reports/npm-test.log >> failure_summary.md || true
            echo '```' >> failure_summary.md
          fi

      - name: Build Job Summary (Checks tab)
        if: always()
        run: |
          echo "## PR Validate Summary" >> $GITHUB_STEP_SUMMARY
          if [ "${{ env.SKIP }}" == "1" ]; then
            echo "- ⏭️ **Docs-only changes detected - CI steps skipped**" >> $GITHUB_STEP_SUMMARY
          else
            echo "- Py tests exit: ${{ steps.pytest.outputs.exit_code || 'n/a' }}" >> $GITHUB_STEP_SUMMARY
            echo "- JS tests exit: ${{ steps.npmtest.outputs.exit_code || 'n/a' }}" >> $GITHUB_STEP_SUMMARY
            echo "- DB: pgvector/pg16 service up" >> $GITHUB_STEP_SUMMARY
            echo "- Alembic rollback: smoke test completed" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- Logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts: reports (JUnit/XML, logs)" >> $GITHUB_STEP_SUMMARY

      - name: Label PR on failure
        if: failure() || steps.pytest.outputs.exit_code == '1' || steps.npmtest.outputs.exit_code == '1'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: ['ci-failed']
            });

      - name: Post structured comment (Claude/Codex/GPT prompts)
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const pr = context.payload.pull_request;
            const run = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            const py = `${{ steps.pytest.outputs.exit_code || 'n/a' }}`;
            const js = `${{ steps.npmtest.outputs.exit_code || 'n/a' }}`;
            
            let failureSummary = '';
            try {
              failureSummary = fs.readFileSync('failure_summary.md', 'utf8');
            } catch (e) {
              // If no failure summary file, continue without it
            }
            
            const body = `
**PR Validate Report**

${process.env.SKIP === '1' ? '⏭️ **Docs-only changes detected - CI steps skipped for efficiency**\n\n' : `- **Python tests exit**: ${py}
- **Node tests exit**: ${js}
- **DB**: Postgres16 + pgvector service is running
- **Alembic rollback**: smoke test completed\n`}- **Logs**: ${run}
- **Artifacts**: download "reports" (JUnit/XML, logs)

If failed, check:
1) Lint output (inline annotations in "Files changed" & "Checks")
2) Unit test failures (reports/pytest.xml or npm test log)
3) DB migrations (alembic upgrade head)
4) Reproduce locally as in \`AGENTS.md\`

${failureSummary ? `\n${failureSummary}\n` : ''}

---

<details><summary><b>🟣 [ClaudeFix Prompt] — 클로드코드용</b></summary>

Copy & paste into Claude Code. Work on branch <b>${pr.head.ref}</b>.

\`\`\`
Role: Senior Dev (Claude Code)
Goal: Make CI green for PR #${pr.number} — "${pr.title}"

Context
- Repo: ${process.env.GITHUB_REPOSITORY}
- Branch: ${pr.head.ref}
- CI run: ${run}
- DB: Postgres16+pgvector, DATABASE_URL=${process.env.DATABASE_URL}
- Artifacts: "reports" (JUnit/XML, logs)
- Follow AGENTS.md (install, lint, test; DO-NOT-TOUCH paths)

Tasks
1) Reproduce locally per AGENTS.md (including DB).
2) Minimal edits to pass tests/migrations/lint.
3) Push commits to branch ${pr.head.ref} (feat/fix/chore).
4) Reply in PR with before/after & what changed.
\`\`\`
</details>

<details><summary><b>🔵 [CodexFix Prompt] — Codex용</b></summary>

Use ChatGPT Codex connected to this repo. Target branch: <b>${pr.head.ref}</b>.

\`\`\`
System: You are a strict fixer agent in a sandbox. Obey AGENTS.md, avoid protected paths.
User: PR #${pr.number} is failing. CI: ${run}. DB is Postgres16+pgvector, DATABASE_URL=${process.env.DATABASE_URL}.
Goal: Make tests, migrations, and lint pass with minimal changes, then commit to ${pr.head.ref}.
\`\`\`
</details>

<details><summary><b>🟢 [GPTFix Prompt] — GPT에게 붙여넣기</b></summary>

\`\`\`
Role: Pair-Programmer
Ask: Generate the minimal unified diff to make PR #${pr.number} green (tests, migrations, lint).
Inputs:
- Repo: ${process.env.GITHUB_REPOSITORY}
- Branch: ${pr.head.ref}
- CI run: ${run}
- DB: Postgres16+pgvector (DATABASE_URL=${process.env.DATABASE_URL})
- Notes: Respect AGENTS.md; keep commits small and clear.
Deliverables:
1) Short diagnosis.
2) Unified diff patches for each file.
3) Commit message suggestions (Conventional Commits).
\`\`\`
</details>
`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body
            });

      - name: Fail if any suite failed
        if: ${{ steps.pytest.outputs.exit_code == '1' || steps.npmtest.outputs.exit_code == '1' }}
        run: exit 1